#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the markdown engine's data modules from cl-markding's tables.

    python3 tools/gen_markdown_data.py <cl-markding checkout> [--check]

Four modules come out of this, all under src/:

    beamai_markdown_unicode.erl   Unicode category ranges (punctuation, Zs)
    beamai_markdown_entities.erl  the 2125 HTML5 named entities
    beamai_markdown_emoji_data.erl  emoji shortcodes and smileys
    beamai_markdown_bidi_data.erl   RTL / LTR ranges for the globalization ext

The tables are markdig's (via cl-markding, which extracted them from
markdig's C# sources), not Python's: the point of the engine is to agree
with markdig, so it must classify characters exactly as markdig does, not
as whatever Unicode version the local Python was built with.

The generated modules are committed. Running the test suite needs neither
Python nor cl-markding; this script exists so the tables can be audited and
regenerated. --check regenerates into memory and fails if anything on disk
differs.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")

BANNER = ("%%% Generated by tools/gen_markdown_data.py from cl-markding's {src}.\n"
          "%%% DO NOT EDIT BY HAND.\n")


def lisp_vector(text, name):
    """Return the raw body of `(defparameter NAME ... '( ... ))` or `#( ... )`."""
    m = re.search(r"\(defparameter \+" + re.escape(name) + r"\+", text)
    if not m:
        raise SystemExit("table %s not found" % name)
    start = m.end()
    # find the first vector opener after the name
    i = text.index("(", start)
    # walk to the opener of the actual data list: either "'(" (after
    # :initial-contents, so the element-type spec is skipped) or "#("
    ic = text.find(":initial-contents", start)
    cands = [text.find("#(", start)]
    if ic >= 0:
        cands.append(text.find("'(", ic))
    j = min(x for x in cands if x >= 0)
    depth = 0
    k = j + 1
    while True:
        c = text[k]
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                break
        elif c == '"':
            k = text.index('"', k + 1)
            while text[k - 1] == "\\":
                k = text.index('"', k + 1)
        k += 1
    _ = i
    return text[j + 2:k]


def lisp_ints(body):
    out = []
    for tok in body.split():
        if tok.startswith(";"):
            continue
        if tok.startswith("#x"):
            out.append(int(tok[2:], 16))
        else:
            out.append(int(tok))
    return out


def lisp_strings(body):
    """Parse a body of Lisp string literals."""
    out = []
    i = 0
    n = len(body)
    while i < n:
        c = body[i]
        if c == '"':
            j = i + 1
            buf = []
            while body[j] != '"':
                if body[j] == "\\":
                    j += 1
                buf.append(body[j])
                j += 1
            out.append("".join(buf))
            i = j + 1
        else:
            i += 1
    return out


def pairs(seq):
    return list(zip(seq[0::2], seq[1::2]))


def erl_string(s):
    """An Erlang string literal for s, ASCII-safe: non-ASCII as \\x{..}."""
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif 32 <= o < 127:
            out.append(ch)
        else:
            out.append("\\x{%X}" % o)
    return '"' + "".join(out) + '"'


def erl_codepoints(s):
    return "[" + ",".join(str(ord(c)) for c in s) + "]"


def range_clauses(fun, ranges):
    lines = []
    for lo, hi in ranges:
        if lo == hi:
            lines.append("%s(%d) -> true;" % (fun, lo))
        else:
            lines.append("%s(C) when C >= %d, C =< %d -> true;" % (fun, lo, hi))
    lines.append("%s(_) -> false." % fun)
    return "\n".join(lines)


def gen_unicode(cl):
    text = open(os.path.join(cl, "src/helpers/unicode-tables.lisp"), encoding="utf-8").read()
    cm = pairs(lisp_ints(lisp_vector(text, "commonmark-punctuation-ranges")))
    up = pairs(lisp_ints(lisp_vector(text, "unicode-punctuation-ranges")))
    zs = pairs(lisp_ints(lisp_vector(text, "zs-ranges")))
    return "\n".join([
        BANNER.format(src="src/helpers/unicode-tables.lisp"),
        "%%% Only code points >= 128 are tabulated; ASCII is decided in",
        "%%% beamai_markdown_char. The ranges are markdig's, which is what the",
        "%%% flanking rules have to agree with.",
        "-module(beamai_markdown_unicode).",
        "",
        "-export([is_commonmark_punctuation/1, is_unicode_punctuation/1, is_space_separator/1]).",
        "",
        "%% @doc Pc Pd Ps Pe Pi Pf Po plus Sm Sc Sk So (CommonMark 0.31 punctuation).",
        "-spec is_commonmark_punctuation(char()) -> boolean().",
        range_clauses("is_commonmark_punctuation", cm),
        "",
        "%% @doc Pc Pd Ps Pe Pi Pf Po only.",
        "-spec is_unicode_punctuation(char()) -> boolean().",
        range_clauses("is_unicode_punctuation", up),
        "",
        "%% @doc Unicode Zs.",
        "-spec is_space_separator(char()) -> boolean().",
        range_clauses("is_space_separator", zs),
        "",
    ])


def gen_entities(cl):
    text = open(os.path.join(cl, "src/helpers/entities-data.lisp"), encoding="utf-8").read()
    strs = lisp_strings(lisp_vector(text, "entity-data"))
    table = pairs(strs)
    lines = [
        BANNER.format(src="src/helpers/entities-data.lisp"),
        "%%% The HTML5 named character references, without the trailing `;'.",
        "%%% Values are lists of code points: a few entities expand to two.",
        "-module(beamai_markdown_entities).",
        "",
        "-export([lookup/1, count/0]).",
        "",
        "-spec count() -> pos_integer().",
        "count() -> %d." % len(table),
        "",
        "%% @doc The code points an entity name stands for, or `undefined'.",
        "-spec lookup(binary()) -> [char()] | undefined.",
    ]
    for name, value in table:
        lines.append("lookup(<<\"%s\">>) -> %s;" % (name, erl_codepoints(value)))
    lines.append("lookup(_) -> undefined.")
    lines.append("")
    return "\n".join(lines)


def gen_emoji(cl):
    text = open(os.path.join(cl, "src/extensions/emoji-data.lisp"), encoding="utf-8").read()
    short = pairs(lisp_strings(lisp_vector(text, "emoji-shortcode-data")))
    smiley = pairs(lisp_strings(lisp_vector(text, "emoji-smiley-data")))
    lines = [
        BANNER.format(src="src/extensions/emoji-data.lisp"),
        "%%% markdig's EmojiMapping: `:shortcode:' -> emoji and smiley -> shortcode.",
        "-module(beamai_markdown_emoji_data).",
        "",
        "-export([shortcodes/0, smileys/0]).",
        "",
        "%% @doc [{Shortcode, Emoji}] in markdig's order.",
        "-spec shortcodes() -> [{binary(), binary()}].",
        "shortcodes() ->",
        "    [" + ",\n     ".join("{<<%s/utf8>>, <<%s/utf8>>}" % (erl_string(k), erl_string(v))
                                   for k, v in short) + "].",
        "",
        "%% @doc [{Smiley, Shortcode}] in markdig's order.",
        "-spec smileys() -> [{binary(), binary()}].",
        "smileys() ->",
        "    [" + ",\n     ".join("{<<%s/utf8>>, <<%s/utf8>>}" % (erl_string(k), erl_string(v))
                                   for k, v in smiley) + "].",
        "",
    ]
    return "\n".join(lines)


def gen_bidi(cl):
    text = open(os.path.join(cl, "src/extensions/globalization-data.lisp"), encoding="utf-8").read()
    rtl = pairs(lisp_ints(lisp_vector(text, "rtl-character-ranges")))
    ltr = pairs(lisp_ints(lisp_vector(text, "ltr-character-ranges")))
    return "\n".join([
        BANNER.format(src="src/extensions/globalization-data.lisp"),
        "%%% markdig's CharHelper RTL / LTR ranges, for the globalization extension.",
        "-module(beamai_markdown_bidi_data).",
        "",
        "-export([is_rtl/1, is_ltr/1]).",
        "",
        "-spec is_rtl(char()) -> boolean().",
        range_clauses("is_rtl", rtl),
        "",
        "-spec is_ltr(char()) -> boolean().",
        range_clauses("is_ltr", ltr),
        "",
    ])


GENERATORS = {
    "beamai_markdown_unicode.erl": gen_unicode,
    "beamai_markdown_entities.erl": gen_entities,
    "beamai_markdown_emoji_data.erl": gen_emoji,
    "beamai_markdown_bidi_data.erl": gen_bidi,
}


def main(argv):
    args = [a for a in argv if not a.startswith("--")]
    check = "--check" in argv
    if len(args) != 1:
        sys.stderr.write(__doc__)
        return 2
    cl = args[0]
    bad = 0
    for name, gen in GENERATORS.items():
        out = gen(cl)
        path = os.path.join(SRC, name)
        if check:
            on_disk = open(path, encoding="utf-8").read() if os.path.exists(path) else None
            if on_disk != out:
                sys.stderr.write("stale: %s\n" % path)
                bad += 1
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(out)
            print("wrote %s" % path)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
